## todo
* Anaconda Powershell Prompt 如何打开 ？
* 总感觉有的课程缺失，不知道 dtype 什么意思？

# 4.1 pip 基础

pip与扩展程序库
1. 什么是pip
* pip 是python扩展程序库的管理工具
* Python扩展程序为工程实践提供了大量扩展功能函数
* pip通常是自带的
* pip的命令建议在cmd命令卡框下执行

## 检查pip 是否安装，以及对应的版本

In [6]:
pip --version

pip 21.0.1 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Note: you may need to restart the kernel to use updated packages.


## 安装扩展库
* pip install fuzzywuzzy （安装指定软件的最新版本）
* pip install matplotlib==3.4.1 （安装指定版本号的软件）
* pip install "matplotlib>=3.0.1" (安装指定区域版本号)

## 升级扩展库
* pip install --upgrade matplotlib 

## 卸载扩展库
* pip uninstall matplotlib

## 列出已经安装的扩展库
* pip list 

## 列出需要升级的扩展库
* pip list -o 


# 4.2 数组基础

Numpy Numberical Python N纬数组与矩阵运算


In [14]:
# 将numpy导入并且重命名，可以用来检测Numpy 是否安装
import numpy as np

安装与卸载 numpy 
* pip install numpy
* pip uninstall unmpy 

In [2]:
import numpy as np

x = np.array([1,2,3])
x   
# x. 输出 array([1, 2, 3]) 
type(x)


numpy.ndarray

In [28]:
# 获取数组中指定索引下的值
x[0]

1

In [34]:
import numpy as np
# 这里定义一个二维数组，但是却报错了，不知道为什么，报错信息 
# TypeError: Field elements must be 2- or 3-tuples, got '2'
# 错误的写法 b = np.array([1,2],[2,3])
# 正确的写法 
c = np.array([[1,2],[2,3]])
c

array([[1, 2],
       [2, 3]])

In [6]:
import numpy as np
# 飞： 这里定义的应该是一个二维数组
d = np.array([[1,2]])
d

array([[1, 2]])

In [35]:
# 获取二维数组的取值
c[0]

array([1, 2])

In [36]:
c[1]

array([2, 3])

In [41]:
# 当获取数组中不存的值时，会报错， 
# IndexError: index 5 is out of bounds for axis 0 with size 2
c[5]

IndexError: index 5 is out of bounds for axis 0 with size 2

In [42]:
# 定义一个三维数组
import numpy as np
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
d[0]

array([[1, 2],
       [3, 4]])

In [44]:
d[0][0]

array([1, 2])

In [45]:
d[0][0][0]

1

In [7]:
# 将一维数组转换为二维数组 
import numpy as np
e = np.array([1,2])
type(e)  # numpy.ndarray
f = np.array(e,ndmin=2)
f
#或者 m = np.array([2,1], ndmin=2)
#type(f)   # numpy.ndarray

# 这里一维数组和二维数组的类型是相同的，都是 numpy.ndarray

array([[1, 2]])

# 4.3 数组创建与转换

In [65]:
# 手动创建一个三维数组 
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [68]:
# 查看数组的维度， 确定数组是几维数组  Dimension（维度）
a.ndim

3

In [17]:
import numpy as np 
a = np.array([[[1,2],[3,4],[1,2]],[[5,6],[7,8],[3,2]]])
# 这里的a.shape 是什么意思, 经过确认，这里的 结果分别表示 x，y，z 轴每个维度有几条数据 ,它们的乘积表示数组中元素的个数
a.shape

(2, 3, 2)

In [16]:
# 飞：这里的a 必须是已经定义好的数组变量
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a.shape=(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
# 切换数组的形状，
a.shape=(4,2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
a.shape=(1,3)

ValueError: cannot reshape array of size 8 into shape (1,3)

In [81]:
a.shape=(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

* 通过上面的两个错误示例，说明使用shape转换形状的时候，总数应该一致

## 创建一些特殊的数组 

In [86]:
import numpy as np
c = np.zeros([4,2],dtype=float)
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
# 创建一个数据类型维int 的零数组
import numpy as np
d = np.zeros([4,2], dtype=int);
d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [91]:
# 创建一个一数组。 （一数组乘以任何数组都是数组本身）
np.ones([3,2],dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [95]:
import numpy as np
# 产生一个简单的一数组
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [97]:
import numpy as np
# 创建一个对角矩阵, 对角全是1，其他的都是0。
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [100]:
import numpy as np
# 将列表转换为数组
a = [1,2,3,4]
b = np.asarray(a)
b

array([1, 2, 3, 4])

In [103]:
import numpy as np
# 将元组转换为数组
a = (1,3,5,7,9)
b = np.asarray(a)
b 

array([1, 3, 5, 7, 9])

In [104]:
import numpy as np
# 将 元组列表 转换为数组
a = [(1,3),(2,4)]
b = np.asarray(a)
b

array([[1, 3],
       [2, 4]])

### 下面的关于np.frombuffer 方法不懂 ？？？

In [112]:
import numpy as np
x = b'My python!'
# 这里的 dtype 的是S2， 这里的s不能小写
y = np.frombuffer(x,dtype='S2')
y

array([b'My', b' p', b'yt', b'ho', b'n!'], dtype='|S2')

In [115]:
import numpy as np
x = b'My python!'
y = np.frombuffer(x, dtype='S2',count=3)
y

array([b'My', b' p', b'yt'], dtype='|S2')

In [116]:
import numpy as np
x = 'My python!'
y = np.frombuffer(x, dtype='S2', count=3)

TypeError: a bytes-like object is required, not 'str'

* 从上面的报错可以知道，np.frombuffer 输入的参数应该是一个bytes (字节类型的数据，而不是字符串类型数据)

In [122]:
import numpy as np
x = b'My python!'
y = np.frombuffer(x, dtype='S2',count=3)
y  # 通过 y.ndim 知道该数组是一个一维数组 

array([b'My', b' p', b'yt'], dtype='|S2')

In [125]:
import numpy as np
# 通过其他形式生成数组,这里通过迭代生成数组 
x = list(range(8))
y = iter(x)
z = np.fromiter(y, dtype=int)
z.shape=(2,4)
z

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [128]:
import numpy as np
# 通过np 的 arange 生成数组
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [129]:
import numpy as np
# 生成一个从1开始的数组
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [132]:
import numpy as np
# 生成一个等差数组, 从4 开始， 20 结束， 步长是 2。
a = np.arange(4,20,2)
a

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [136]:
# 调整布局
a.shape=(2,4)
a

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [142]:
import numpy as np

# 从1到5 之间创建指定步长的数组，这里的endpoint 为True 表示包含结尾的数  
x = np.linspace(1,5,8, endpoint = True, dtype=int)
x

array([1, 1, 2, 2, 3, 3, 4, 5])

In [147]:
import numpy as np
x = np.linspace(a,5,10, endpoint=True, dtype=float)
x.ndim # 三维数组
x

array([[[ 4.        ,  6.        ,  8.        , 10.        ],
        [12.        , 14.        , 16.        , 18.        ]],

       [[ 4.11111111,  5.88888889,  7.66666667,  9.44444444],
        [11.22222222, 13.        , 14.77777778, 16.55555556]],

       [[ 4.22222222,  5.77777778,  7.33333333,  8.88888889],
        [10.44444444, 12.        , 13.55555556, 15.11111111]],

       [[ 4.33333333,  5.66666667,  7.        ,  8.33333333],
        [ 9.66666667, 11.        , 12.33333333, 13.66666667]],

       [[ 4.44444444,  5.55555556,  6.66666667,  7.77777778],
        [ 8.88888889, 10.        , 11.11111111, 12.22222222]],

       [[ 4.55555556,  5.44444444,  6.33333333,  7.22222222],
        [ 8.11111111,  9.        ,  9.88888889, 10.77777778]],

       [[ 4.66666667,  5.33333333,  6.        ,  6.66666667],
        [ 7.33333333,  8.        ,  8.66666667,  9.33333333]],

       [[ 4.77777778,  5.22222222,  5.66666667,  6.11111111],
        [ 6.55555556,  7.        ,  7.44444444,  7.88888

In [149]:
# 生成一个等比数列, 一共 10个数 
import numpy as np
x = np.logspace(0, 2.0, num = 10)
x

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [151]:
# 生成一个等比数列, 一共 10个数 , 不懂 ？？？？
import numpy as np
x = np.logspace(0, 2.0, num = 10, base = 4)
x

array([ 1.        ,  1.36079   ,  1.85174942,  2.5198421 ,  3.42897593,
        4.66611616,  6.34960421,  8.64047791, 11.75787594, 16.        ])

# 4.4 数组与切片

飞： 数组的切片---降维

In [156]:
import numpy as np
x = np.arange(12)
print(x)
type(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


numpy.ndarray

In [160]:
import numpy as np
x = np.arange(12)
print(x)
# 从2 到10 ，每隔3 获取一个元素
y = x[2:10:3]
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 5 8]


In [167]:
# slice 
import numpy as np
x = np.arange(12)
print('x = ',x)
s = slice(2,10,3)
y = x[s]
print('y = ' , y)
print('x[3] = ', x[3])
print('x[3:]', x[3:])

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
y =  [2 5 8]
x[3] =  3
x[3:] [ 3  4  5  6  7  8  9 10 11]


In [178]:
# 
import numpy as np
x = np.array([[1,2,3],[3,4,5],[5,6,7]])
print('x = ', x) 
print('x的类型：', type(x))
row = [1,0,1]
col = [2,1,0]
# 这里x[row,col] 表示取x数组中，第二行第三列， 第一行第二列，第二行第一列的曲取值 
y = x[row,col]
y


x =  [[1 2 3]
 [3 4 5]
 [5 6 7]]
x的类型： <class 'numpy.ndarray'>


array([5, 2, 3])